recoveries_server: # "behavior_server" for newer distro of ROS2
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["backup", "wait"]  # exclude "spin"
    spin:
      plugin: "nav2_recoveries/Spin" # "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp" # "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait" # "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: ego_racecar/base_link
    transform_timeout: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2