# --------------------------------------------------------------------------------------------------------------------------------------------------
# Getting Base image (ubuntu 20.04)
# --------------------------------------------------------------------------------------------------------------------------------------------------
FROM ghcr.io/ucsd-ecemae-148/donkeycontainer:ros
SHELL ["/bin/bash", "-c"] 

WORKDIR /
# --------------------------------------------------------------------------------------------------------------------------------------------------
# apt update & upgrade
# --------------------------------------------------------------------------------------------------------------------------------------------------
RUN apt update &&\
    apt upgrade -y

####################################################################################################################################################
# Install required packages/dependencies for f1tenth_ros
####################################################################################################################################################
#
#

# --------------------------------------------------------------------------------------------------------------------------------------------------
# install useful packages
# --------------------------------------------------------------------------------------------------------------------------------------------------
RUN apt update && \
    apt install -y --no-install-recommends \
    ros-foxy-rmw-cyclonedds-cpp \
    ros-foxy-rosbridge-suite

WORKDIR /home

RUN apt-get install ros-foxy-behaviortree-cpp-v3 \
    libtool \
    pkg-config \
    build-essential \
    autoconf \
    automake \
    libzmq-dev \
    qtbase5-dev \
    libqt5svg5-dev \
    libzmq3-dev \
    libdw-dev

RUN git clone --recurse-submodules https://github.com/BehaviorTree/Groot.git
WORKDIR /home/Groot
RUN cmake -S . -B build
RUN cmake --build build

WORKDIR /home/projects/f1tenth_ws

COPY ./ ./

########### Build Basic ROS 2 Packages ###########
RUN source source_ros2.sh && \
    vcs import < common.repos && \
    vcs import < lidar_utils.repos && \
    make rosdep-install && \ 
    build_ros2

########### Build livox_sdk2, livox_ros_driver2 ###########
RUN source source_ros2.sh && \
    vcs import < racer.repos && \ 
    make livox-driver
