# --------------------------------------------------------------------------------------------------------------------------------------------------
# Getting Base image (ubuntu 20.04)
# --------------------------------------------------------------------------------------------------------------------------------------------------
FROM ghcr.io/ucsd-ecemae-148/donkeycontainer:ros
SHELL ["/bin/bash", "-c"] 

WORKDIR /
# --------------------------------------------------------------------------------------------------------------------------------------------------
# apt update & upgrade
# --------------------------------------------------------------------------------------------------------------------------------------------------
RUN apt update &&\
    apt upgrade -y

####################################################################################################################################################
# Install required packages/dependencies for f1tenth_ros
####################################################################################################################################################
#
#

# --------------------------------------------------------------------------------------------------------------------------------------------------
# install useful packages
# --------------------------------------------------------------------------------------------------------------------------------------------------
RUN apt update && \
    apt install -y --no-install-recommends \
    ros-foxy-rmw-cyclonedds-cpp \
    ros-foxy-rosbridge-suite \
    ros-foxy-nav2* \
    ros-foxy-navigation2 \
    ros-foxy-smac-planner \
    ros-foxy-spatio-temporal-voxel-layer \
    ros-foxy-nonpersistent-voxel-layer \
    ros-foxy-tf-transformations

WORKDIR /home

RUN apt-get update --fix-missing
RUN apt-get install -y ros-foxy-behaviortree-cpp-v3 \
    libtool \
    pkg-config \
    build-essential \
    autoconf \
    automake \
    # libzmq-dev \
    qtbase5-dev \
    libqt5svg5-dev \
    libzmq3-dev \
    libdw-dev

RUN pip install trajectory_planning_helpers==0.76 \
    casadi \ 
    scikit-image \
    transforms3d


RUN git clone --recurse-submodules https://github.com/BehaviorTree/Groot.git
WORKDIR /home/Groot
RUN cmake -S . -B build
RUN cmake --build build

WORKDIR /home/projects/f1tenth_ws

COPY ./ ./

########### Build Basic ROS 2 Packages ###########
RUN source source_ros2.sh && \
    vcs import < repos/common.repos && \
    vcs import < repos/lidar_utils.repos && \
    vcs import < repos/racer.repos && \ 
    make gb_opt && \
    make rosdep-install && \ 
    build_ros2

########### Build livox_sdk2, livox_ros_driver2 ###########
RUN source source_ros2.sh && \
    vcs import < repos/livox.repos && \ 
    make livox-driver

# f1tenth gym
WORKDIR /home/projects/f1tenth_ws/src/f1tenth_sim
RUN git clone https://github.com/f1tenth/f1tenth_gym
RUN cd f1tenth_gym && \
    pip3 install -e .

# ros2 gym bridge
WORKDIR /home/projects/f1tenth_ws/src/f1tenth_sim
RUN git clone https://github.com/f1tenth/f1tenth_gym_ros
RUN cd ../.. && \
    source source_ros2.sh && \
    apt-get update --fix-missing && \
    build_ros2

WORKDIR /home/projects/f1tenth_ws/
RUN echo 'export LD_PRELOAD=/usr/local/lib/python3.8/dist-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0' >> ~/.bashrc
ENTRYPOINT ["/bin/bash"]