<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">

    <xacro:property name="wheelbase" value="0.3302" />
    <xacro:property name="width" value="0.2032" />
    <xacro:property name="height" value="0.05" />
    <!-- <xacro:property name="ground_offset" value="0.04" /> -->
    <xacro:property name="wheel_radius" value="0.0508" />
    <xacro:property name="wheel_length" value="0.0381" />
    <xacro:property name="laser_distance_from_base_link" value="0.275" />
    <!-- <xacro:property name="laser_height" value="0.05" /> -->
    <!-- <xacro:property name="laser_radius" value="0.026" /> -->
    <xacro:property name="car_name" value="ego_racecar" />

    <material name="black">
        <color rgba="0.0 0.0 0.0 1"/>
    </material>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1"/>
    </material>

    <material name="grey">
        <color rgba="0.25 0.25 0.25 1"/>
    </material>
    
    <material name="blue">
        <color rgba="0.3 0.57 1. 1."/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">
        <inertial>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <mass value="0.18" />
            <inertia ixx="0.0002835" ixy="0.0" ixz="0.0" iyy="0.0002835" iyz="0.0" izz="0.000324"/>
        </inertial>
        <collision>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.06" length="0.09"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${wheelbase} ${width} ${height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <!-- BASE FOOTPRINT LINK-->

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- LIDAR LINK -->

    <link name="lidar_link">
	<visual>
            <origin rpy="0 0 ${pi/2}" xyz="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.065 0.065 0.06"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.05 0.0 0.10" rpy="0 0 0"/>
    </joint>

    <!-- CAMERA LINK -->

    <link name="camera_link">
	    <visual>
            <origin rpy="0 0 ${pi/2}" xyz="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.097 0.03 0.023"/>
            </geometry>
            <material name="grey"/>
        </visual>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.120 0.0 0.145" rpy="0 0 0"/>
    </joint>

    <!-- WHEEL FL LINK -->

    <link name="${car_name}/wheel_FL">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <link name="${car_name}/hinge_FL"/>

    <joint name="base_to_hinge_FL" type="fixed">
        <parent link="base_link"/>
        <child link="${car_name}/hinge_FL"/>
        <origin xyz="${wheelbase/2} ${(wheel_length+width)/2} 0.0" rpy="0 0 0"/>
    </joint>

    <joint name="wheel_FL_joint" type="revolute">
        <parent link="${car_name}/hinge_FL"/>
        <child link="${car_name}/wheel_FL"/>
        <limit lower="-0.2" upper="0.2" effort="0.1" velocity="0.05"/>
        <axis xyz="1 0 0"/>
    </joint>

    <!-- WHEEL FR LINK -->

    <link name="${car_name}/wheel_FR">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <link name="${car_name}/hinge_FR"/>

    <joint name="base_to_hinge_FR" type="fixed">
        <parent link="base_link"/>
        <child link="${car_name}/hinge_FR"/>
        <origin xyz="${wheelbase/2} -${(wheel_length+width)/2} 0.0" rpy="0 0 0"/>
    </joint>

    <joint name="wheel_FR_joint" type="revolute">
        <parent link="${car_name}/hinge_FR"/>
        <child link="${car_name}/wheel_FR"/>
        <limit lower="-0.2" upper="0.2" effort="0.1" velocity="0.05"/>
        <axis xyz="1 0 0"/>
    </joint>

    <!-- WHEEL RL LINK -->

    <link name="${car_name}/wheel_RL">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="wheel_RL_joint" type="revolute">
        <parent link="base_link"/>
        <child link="${car_name}/wheel_RL"/>
        <origin xyz="-${wheelbase/2} ${(wheel_length+width)/2} 0.0" rpy="0 0 0"/>
        <limit lower="-0.2" upper="0.2" effort="0.1" velocity="0.05"/>
        <axis xyz="1 0 0"/>
    </joint>

    <!-- WHEEL RR LINK -->

    <link name="${car_name}/wheel_RR">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="wheel_RR_joint" type="revolute">
        <parent link="base_link"/>
        <child link="${car_name}/wheel_RR"/>
        <origin xyz="-${wheelbase/2} -${(wheel_length+width)/2} 0.0" rpy="0 0 0"/>
        <limit lower="-0.2" upper="0.2" effort="0.1" velocity="0.005"/>
        <axis xyz="1 0 0"/>
    </joint>

    <!-- GAZEBO -->

    <gazebo reference="base_link">
        <kp>100000.0</kp>
        <kd>100000.0</kd>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- camera -->
    <gazebo reference="camera_link">
        <sensor type="camera" name="camera1">
        <update_rate>15.0</update_rate>
        <camera name="head">

            <pose>0 0 0 0 0 0</pose>

            <horizontal_fov>1.3962634</horizontal_fov>
            <image>
            <width>400</width>
            <height>400</height>
            <format>R8G8B8</format>
            </image>
            <clip>
            <near>0.01</near>
            <far>100</far>
            </clip>
            <noise>
            <type>gaussian</type>
            <stddev>0.007</stddev>
            </noise>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>0.0</updateRate>
            <cameraName>my_robot/camera1</cameraName>
            <imageTopicName>image_raw</imageTopicName>
            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
            <frameName>camera_link</frameName>
            <hackBaseline>0.07</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
        </plugin>
        </sensor>
    </gazebo>

    <gazebo reference="lidar_link">
        <material value="Gazebo/Blue" />
        <sensor type="ray" name="lidar">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <ray>
            <scan>
                <horizontal>
                <samples>811</samples>
                <resolution>1</resolution>
                <min_angle>-2.35</min_angle>
                <max_angle>2.35</max_angle>
                </horizontal>
            </scan>
            <range>
                <min>0.02</min>
                <max>30.0</max>
                <resolution>0.01</resolution>
            </range>
            </ray>
            <plugin name="scan" filename="libgazebo_ros_gpu_laser.so">
            <topicName>/ego_racecar/scan</topicName>
            <frameName>lidar_link</frameName>
            </plugin>
        </sensor>
        </gazebo>

</robot>
