<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>autonomy_launch</name>
  <version>0.0.0</version>
  <description>Launch autonomy stack</description>
  <maintainer email="winston.h.chou@gmail.com">Winston Chou</maintainer>
  <license>LGPLv3</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <exec_depend>base_common</exec_depend>
  <exec_depend>common_metadata</exec_depend>
  <!-- <exec_depend>vehicle_kinematic_state</exec_depend> -->
  <exec_depend>environs</exec_depend>
  <exec_depend>robot_localization_interface</exec_depend>
  <depend>robot_localization</depend>
  <!-- <exec_depend>boundary_publisher</exec_depend> -->

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
