# Avalible Plugins for planner in ROS2 Foxy
# - NavFn Planner (nav2_navfn_planner/NavfnPlanner)
# - SmacPlanner (smac_planner/SmacPlanner)
# - SmacPlanner2D (smac_planner/SmacPlanner2D)
# 

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: False
    planner_plugins: ["GridBased"]  # List of mapped plugin names for parameters and processing requests. Each plugin namespace defined in this list needs to have a plugin parameter defining the type of plugin to be loaded in the namespace, in the following way:
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5                # Tolerance in meters between the goal pose and the end of the path.
      use_astar: false              # Whether to use A*. If false, use Dijkstra’s expansion.
      allow_unknown: true           # Whether to allow planning in an unknown space.
    # GridBased:
    #   plugin: "nav2_theta_star_planner::ThetaStarPlanner" # In Iron and older versions, "/" was used instead of "::"
    #   how_many_corners: 8
    #   w_euc_cost: 1.0
    #   w_traversal_cost: 2.0
    #   w_heuristic_cost: 1.0

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.25
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer", "obstacle_layer", "voxel_layer"]

      # Static Layer - Adds as obstacles to the Global Costmap any black dot that exists in the static map
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        map_subscribe_transient_local: True
      
      # Inflation Layer - Adds an inflation to any obstacle in the Global Costmap, as a safe distance to maintain
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        cost_scaling_factor: 3.0  # Exponential decay factor across the inflation radius.
        inflation_radius: 0.35
      always_send_full_costmap: True

      # Obstacle Layer - Adds to the Global Costmap any object detected by a 2D sensor
      obstacle_layer: 
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scanner/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          inf_is_valid: false
      
      # Voxel Layer - Adds to the Global Costmap 3D obstacles from PointCloud data
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: False
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: pointcloud
        combination_method: 1
        pointcloud:  # no frame set, uses frame from message
          topic: /livox/lidar
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: "PointCloud2"