/**:
  ros__parameters:
    target_frame: 'slice_frame'
    transform_tolerance: 0.01
    min_height: 0.0
    max_height: 0.1
    angle_min: -3.1416 # -M_PI/2
    angle_max: 3.1416 # M_PI/2
    angle_increment: 0.0087  # M_PI/360.0
    scan_time: 0.3333
    range_min: 0.05
    range_max': 15.0
    use_inf: True
    inf_epsilon: 1.0