/**:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: drive
      axis_mappings:
        drive-speed:
          axis: 4
          scale: 4.0
          offset: 0.0
        drive-steering_angle:
          axis: 0
          scale: -0.35
          offset: 0
