# sensors/hardware
all_components: 1
# simulator: 0

# camera navigation
# camera_nav_calibration: 0
# camera_nav: 0

# recording data 
rosbag_launch: 0
ros_bridge_launch: 0

# foxglove Studio
# rosbridge_suite: 1

# TODO: Obstacle Avoidance
# simple_obstacle_detection_launch: 0

# rviz
sensor_visualization: 1

# Wall Following
wall_follow: 0

# control
f1tenth_vesc_joy_launch: 0
# pid_launch: 0
# lqr_launch: 0
# lqg_launch: 0
# lqg_w_launch: 0
# mpc_launch: 0

# path planner
# path_nav: 0
# tube_follower_launch: 0
# curve_localizer_launch: 0

urdf: 0
localization: 0

pointcloud_to_laserscan: 1

# scan_correction: 1
