bridge:
  ros__parameters:
    launch_rviz: True
    ego_urdf_pub: False
    opp_urdf_pub: False

    # topics and namespaces
    ego_namespace: 'ego_racecar'
    ego_scan_topic: 'scan'
    ego_odom_topic: 'odom'
    ego_opp_odom_topic: 'opp_odom'
    ego_drive_topic: 'drive'
    opp_namespace: 'opp_racecar'
    opp_scan_topic: 'opp_scan'
    opp_odom_topic: 'odom'
    opp_ego_odom_topic: 'opp_odom'
    opp_drive_topic: 'opp_drive'

    # for publishing transforms properly, 
    # it'd be consider same format for both agents' namespaces.
    base_frame: 'base_footprint'
    front_left_hinge_link_name: 'hinge_FL'
    front_left_wheel_link_name: 'wheel_FL'
    front_right_hinge_link_name: 'hinge_FR'
    front_right_wheel_link_name: 'wheel_FR'
    lidar_link_name: 'lidar_link'
    laser_frame_name: 'laser'

    # transform related
    scan_distance_to_lidar_link: 0.0
    
    # laserscan parameters
    scan_fov: 4.7
    scan_beams: 1080

    # map parameters
    map_path: '/home/projects/f1tenth_ws/src/external/f1tenth_sim/f1tenth_gym_ros/maps/levine'
    map_img_ext: '.png'

    # opponent parameters
    num_agent: 1

    # ego starting pose on map
    sx: 0.0
    sy: 0.0
    stheta: 0.0

    # opp starting pose on map
    sx1: 2.0
    sy1: 0.5
    stheta1: 0.0

    # teleop
    kb_teleop: True