/**:
    ros__parameters:
      topics:
        navigation:
          topic: /ego_racecar/drive
          timeout : 0.2
          priority: 100
        joystick:
          topic: /ego_racecar/teleop
          timeout : 0.2
          priority: 10
