/**:
  ros__parameters:
    odom_frame: odom
    base_frame: ego_racecar/base_footprint
        
    publish_tf: false   # Disable if using Sensor Fusion
    use_servo_cmd_to_calc_angular_velocity: true
    wheelbase: .34
    speed_to_erpm_gain: 2000.0
    speed_to_erpm_offset: 0.0 

    # servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
    steering_angle_to_servo_gain: 1.2135 
    steering_angle_to_servo_offset: 0.55

    port: /dev/ttyACM0
    duty_cycle_min: 0.0
    duty_cycle_max: 0.0
    current_min: 0.0
    current_max: 100.0
    brake_min: -20000.0
    brake_max: 200000.0
    speed_min: -23250.0
    speed_max: 23250.0
    position_min: 0.0
    position_max: 0.0
    servo_min: 0.05
    servo_max: 0.95
